describe('Goes to the localhost', () => {
	it('Goes to localhost/kata-rasa/index.html', () => {
		cy.visit('localhost/kata-rasa/index.html')
	})
})

describe('Testing the Indonesian site', () => {
	it('Searches all Indonesian elements', () => {
		cy.contains('ID')
		cy.contains('Beranda')
		cy.contains('Rasa-Rasa')
		cy.contains('Kalimat Bijak')
		cy.contains('Kesan Pesan')
		cy.contains('Galeri')
		cy.contains('Ulasan')
		cy.contains('Beli Sekarang')
		cy.contains('Keripik singkong dari Indonesia')
		cy.get('#flavours-nav').click()
		cy.contains('Rasa-Rasa')
		cy.contains('Original')
		cy.contains('Sudah Tersedia')
		cy.contains('Gurih dan garing, sedikit asin.')
		cy.contains('Sambalado')
		cy.contains('Sudah Tersedia')
		cy.contains('Rasanya pedas, ada rasa jeruk-jeruknya gitu.')
		cy.contains('Keju unyu')
		cy.contains('Sudah Tersedia')
		cy.contains('Manis-manis, sedikit asin.')
		cy.contains('Cabe gledek')
		cy.contains('Sudah Tersedia')
		cy.contains('Pokoknya pedas.')
		cy.get('#jokes-nav').click()
		cy.contains('Kalimat Bijak')
		cy.contains('Jangan takut gendut. Tambah gendut, tambah berat, tambah susah diculik. Biar aman ngemil aja yang banyak.')
		cy.get('#comments-nav').click()
		cy.contains('Resya Deng')
		cy.contains('5/5')
		cy.contains('Keripiknya enak!')
		cy.contains('Syana Deng')
		cy.contains('5/5')
		cy.contains('Keripiknya enak, bakal beli lagi.')
		cy.get('#gallery-nav').click()
		cy.contains('Galeri')
		cy.contains('Original')
		cy.get('#gallery > [src="original1.jpg"]')
		cy.get('#gallery > [src="original2.jpg"]')
		cy.get('#gallery > [src="original3.jpg"]')
		cy.contains('Sambalado')
		cy.get('#gallery > [src="sambalado1.jpeg"]')
		cy.get('#gallery > [src="sambalado2.jpeg"]')
		cy.get('#gallery > [src="sambalado3.jpeg"]')
		cy.get('#feedback-nav').click()
		cy.contains('Nama')
		cy.get('#name-label')
		cy.contains('Ulasan')
		cy.get('#review-label')
		cy.contains('Kirim')
		cy.get('#buy-btn-nav').click()
		cy.contains('Beli Sekarang')
		cy.contains('Original')
		cy.get(':nth-child(1) > .image')
		cy.contains('Sambalado')
		cy.get(':nth-child(2) > .image')
		cy.contains('Beli Sekarang')
		cy.contains('Beli Sekarang')
		cy.get('#home-nav').click()
	})
	it('Test the english site', () => {
		cy.get('#language').click()
		cy.contains('EN')
		cy.contains('Home')
		cy.contains('Flavours')
		cy.contains('Wise Words')
		cy.contains('Review')
		cy.contains('Gallery')
		cy.contains('Feedback')
		cy.contains('Buy Now')
		cy.contains('Cassava chips from Indonesia')
		cy.get('#flavours-nav').click()
		cy.contains('Flavours')
		cy.contains('Original')
		cy.contains('Available')
		cy.contains('Crunchy, but a little bit salty.')
		cy.contains('Sambalado')
		cy.contains('Available')
		cy.contains("It's spicy, but has a little bit of an orange flavour.")
		cy.contains("Keju unyu")
		cy.contains("Available")
		cy.contains("Sweet, but a little bit salty.")
	})
})